<?php
$str_less = "
		body {
			background-color: @body_background_color;
			font-family: @body_font_family;
			font-size: @body_font_size;
			color: @text_color;
			line-height: 1.66;
			background-image: url('@{background_path}');
			background-repeat: @background_repeat;
			background-position: @background_position;
		}
		
		@theme_color_active: darken(@theme_color, 5%);
		
		.label {
			color: @text_color;
		}
		
		a,
		a:focus,
		a:visited {
			color: @link_color;
		}
		
		a:hover {
			color: @link_hover_color;
		}
		
		/* GENERAL */
		.smcqp-btn,
		.spcqp-count,
		.owl-controls .owl-nav div:hover {
			background-color: @theme_color;
		}
		
		button:not(.owl-prev),
		button:not(.owl-next),
		button:not(.owl-prev):focus,
		button:not(.owl-next):focus,
		.cart-container .action.continue, a.action.primary, .modal-footer .action-primary.action-accept {
			background-color: @theme_color;
		
			&:hover {
				background-color: @theme_color_active;
			}
		}
		
		.block-minicart .header-minicart {
			background-color: @theme_color;
		}
		
		.block-minicart .minicart-items .product-item-details .price-container .price {
			color: @theme_color;
		}
		
		.block-minicart .block-content > .actions a:hover {
			background-color: @theme_color;
		}
		
		.block-minicart .subtotal .price-container .price-wrapper:first-child .price {
			color: @theme_color;
		}
		
		.time-countdown-slide .time-ranger .time-pass{
			background-color: @theme_color;
		}
		
		#yt-totop-fix {
			background-color: @theme_color;
		
			&:hover {
				background-color: darken(@theme_color, 10%);
			}
		}
		
		#page-loader .loader span {
			background-color: @theme_color;
		}
		
		.fotorama__thumb-border {
			border-color: @theme_color !important;
		}
		
		.fotorama__active .fotorama__dot {
			border-color: @theme_color !important;
			background-color: @theme_color;
		}
		
		.cart-container .cart.table-wrapper .product-item-photo .product-image-photo:hover {
			border-color: @theme_color;
		}
		
		.cartpro-modal .cpmodal-button {
			background-color: @theme_color;
		}
		
		#btn-gallery:hover {
			background-color: @theme_color;
		}
		
		.owl-dots .owl-dot:hover,
		.owl-dots .owl-dot.active {
			background-color: @theme_color;
		}
		
		.cart-container .cart-summary .coupon .actions-toolbar .primary .apply.primary:hover,
		.modal-footer .action-primary.action-accept:hover,
		.slider-ourmember .owl-dots .owl-dot:hover,
		.slider-ourmember .owl-dots .owl-dot.active,
		.control-qty .quantity-controls:hover {
			background-color: @theme_color;
		}
		
		.smrv-block-content-wrap .smrv-handle:hover .smrv-icon,
		.smrv-block-content-wrap.smrv-over .smrv-handle .smrv-icon,
		.sm-recently-viewed .smrv-clear:hover,
		.sm-recently-viewed .product-item-info a:hover .product-image-wrapper:hover:after {
			background-color: @theme_color;
		}
		
		.sm-listing-tabs .ltabs-items .ltabs-loadmore .ltabs-loadmore-btn {
			background-color: @theme_color;
		
			&:hover {
				background-color: darken(@theme_color, 10%);
			}
		}
		
		.block-minicart .minicart-items .product-item-details .product-item-name a:hover {
			color: @theme_color;
		}
		
		.fotorama__nav-wrap--horizontal .fotorama__thumb__arr--right:hover,
		.fotorama__nav-wrap--horizontal .fotorama__thumb__arr--left:hover {
			background-color: @theme_color;
			border-color: @theme_color;
		}
		
		.fotorama-item .fotorama__nav--thumbs .fotorama__nav__frame.fotorama__active {
			border-color: @theme_color;
		}
		
		.more-w .more-view:hover {
			color: @theme_color;
		}
		
		.cartpro-imageload {
			border-color: @theme_color !important;
			color: @theme_color !important;
		}
		
		.direction_rtl .breadcrumbs .items .item:hover,
		.breadcrumbs .items .item:hover {
			border-color: @theme_color;
		
			&:before,
			&:after {
				border-color: @theme_color;
			}
		}
		
		/* END GENERAL */
		
		/* LISTING */
		
		#price-slider .ui-slider-range {
			background-color: @theme_color;
		}
		
		#price-slider .ui-slider-handle {
			color: @theme_color;
		}
		
		#sm_slider_price .ui-slider-range {
			background-color: @theme_color;
		}
		
		#sm_slider_price .ui-slider-handle {
			border-color: @theme_color;
		}
		
		.sidebar .block.filter .block-content.filter-content .filter-options-content .items li a:hover {
			color: @link_hover_color;
		}
		
		.products-grid .item .item-inner .box-info:before {
			background-color: @theme_color;
		}
		
		.breadcrumbs .items .item a:hover {
			color: @link_hover_color;
		}
		
		.products-grid .item .item-inner .box-image .bottom-action .action:hover {
			background-color: @theme_color !important;
			border-color: @theme_color !important;
		}
		
		.products-grid .item .item-inner .box-image .bottom-action .action:after {
			color: @theme_color;
		}
		
		.toolbar .modes .modes-mode.active {
			color: @theme_color;
		}
		
		.toolbar .pages .pages-items .item:hover,
		.toolbar .pages .pages-items .item.current {
			background-color: @theme_color;
			border-color: @theme_color;
		}
		
		.price-box .special-price .price,
		.price-box .price {
			color: @theme_color;
		}
		
		.products-list .item .item-inner .box-info-list .bottom-action .towishlist,
		.products-list .item .item-inner .box-info-list .bottom-action .tocompare {
			&:hover,
			&:before {
				color: @theme_color;
			}
		}
		
		.products-list .item .item-inner .box-image-list .quickview-handler:hover {
			background-color: @theme_color;
			border-color: @theme_color;
		}
		
		.products-list .item .item-inner .box-info-list .product-name a:hover {
			color: @link_hover_color;
		}
		
		.products-list .item .item-inner .box-info-list .bottom-action .tocart {
			color: @theme_color !important;
			border: 1px solid @theme_color !important;
		
			&:hover {
				background-color: @theme_color !important;
			}
		}
		
		.list-slider .products-type-list .item .item-inner .box-image:hover {
			border-color: @theme_color;
		}
		
		/* END LISTING */
		
		/* DETAIL */
		
		.services-sidebar li .service-content .service-icon {
			color: @theme_color;
		}
		
		.accordion-style .resp-accordion.resp-tab-active {
			background-color: @theme_color !important;
			border-color: @theme_color !important;
		}
		
		.detail-title h2:before {
			background-color: @theme_color;
		}
		
		.related-upsell-wrapper .owl-controls .owl-nav div:hover,
		.upsell-wrapper .owl-controls .owl-nav div:hover,
		.resp-vtabs .resp-tabs-list li:hover,
		.resp-vtabs .resp-tabs-list li.resp-tab-active {
			color: @theme_color;
		}
		
		.related-upsell-wrapper .owl-theme .owl-nav div:hover {
			background-color: @theme_color;
			border-color: @theme_color;
		}
		
		.product-info-main .product-addto-links .action,
		.product-info-main .product-social-links .action {
			&:hover {
				border-color: @theme_color;
			}
		
			&:before {
				color: @theme_color;
			}
		
		}
		
		/* horizontal full */
		.product-image-detail {
			.thumbs-container {
				.thumb-slider {
					.thumb-item {
						.thumb-image {
							&:hover,
							&.thumb-active {
								border-color: @theme_color;
							}
						}
					}
				}
			}
		}
		
		/* end horizontal full */
		
		/* END DETAIL */
		
		/* TAB */
		
		.default-style {
			.resp-tabs-list {
				li {
					&.active {
						background-color: @theme_color;
					}
		
					&:not(.active):hover {
						color: @theme_color;
					}
				}
			}
		}
		
		.vertical-style {
			.resp-tabs-list li {
				&.active {
					&:before {
						background-color: @theme_color;
					}
				}
			}
		}
		
		/* END TAB */
		
		/* HEADER */
		
		.sm_megamenu_wrapper_vertical_menu .block-title {
			background-color: @theme_color;
		}
		
		.login-popup-wrapper .block-title:before {
			background-color: @theme_color;
		}
		
		#login-container .close {
			background-color: @theme_color;
		
			&:hover {
				background-color: @theme_color_active;
			}
		}
		
		.dash-line {
			color: @theme_color;
			border-bottom: 1px dashed @theme_color;
		}
		
		.link-customer-action .login-link:hover {
			color: @theme_color;
		}
		
		.link-customer-action .dropdown-account .header.links li.authorization-link a {
			background-color: @theme_color;
		
			&:hover {
				background-color: @theme_color_active;
			}
		}
		
		.navigation-wrapper .block-title {
			background-color: @theme_color_active;
		}
		
		.header-style-1 {
			.minicart-header .cart-wrapper .minicart-wrapper .showcart .counter {
				color: @theme_color;
			}
		
			.link-customer-action .register-link:hover {
				color: @theme_color;
			}
		
			.sublinks-block ul li a:hover {
				color: @link_hover_color;
			}
		
			.sm_megamenu_wrapper_horizontal_menu .sm_megamenu_menu > li {
				&:hover,
				&.sm_megamenu_actived {
					> a {
						color: @theme_color;
					}
				}
			}
		}
		
		.cms-index-index.header-1-style .sm_megamenu_wrapper_horizontal_menu .sm_megamenu_menu li.home-item-parent a.sm_megamenu_head {
			color: @theme_color;
		}
		
		.header-style-2 {
			.minicart-header .cart-wrapper .minicart-wrapper .showcart .text .items-count {
				background-color: @theme_color;
			}
			
			.sm_megamenu_wrapper_horizontal_menu .sm_megamenu_menu > li {
				&:hover,
				&.sm_megamenu_actived {
					> a .sm_megamenu_title{
						color: @theme_color;
					}
				}
			}
		}
		
		.cms-index-index .horizontal-megamenu .sm_megamenu_wrapper_horizontal_menu .sm_megamenu_menu li.home-item-parent a.sm_megamenu_head .sm_megamenu_title {
			color: @theme_color;
		}
		
		.header-style-3 {
			border-bottom: 2px solid @theme_color;
			
			.store-header a{
				&:before{
					color: @theme_color;
				}
				
				&:hover{
					color: @theme_color;
				}
			}
			
			.minicart-header .cart-wrapper .minicart-wrapper .showcart .counter .price-minicart{
				color: @theme_color;
			}
			
			.minicart-header .cart-wrapper .minicart-wrapper .showcart .counter .counter-number{
				background-color: @theme_color;
			}
			
			.sm_megamenu_wrapper_horizontal_menu .sm_megamenu_menu > li{
				&.sm_megamenu_actived,
				&:hover{
					> .sm_megamenu_head{
						color: @theme_color;
					}
				}
			} 
			
			.navigation ul > li.has-active > a, 
			.navigation ul > li.active > a, 
			.navigation ul > li:hover > a,
			.sm_megamenu_wrapper_vertical_menu .sm_megamenu_menu > li > div a:hover,
			.sm_megamenu_wrapper_vertical_menu .sm_megamenu_menu > li.sm_megamenu_actived > a, 
			.sm_megamenu_wrapper_vertical_menu .sm_megamenu_menu > li:hover > a{
				color: @theme_color;
			}
		}
		
		.cms-index-index .header-style-3 .sm_megamenu_wrapper_horizontal_menu .sm_megamenu_menu > li.home-item-parent > .sm_megamenu_head{
			color: @theme_color;
		}
		
		
		/* END HEADER */
		
		/* HOME */
		.home-page-1 {
			.slidershow .owl-theme .owl-nav {
				.owl-next:hover,
				.owl-prev:hover {
					background-color: @theme_color;
				}
			}
		
			.slidershow .owl-theme .owl-dots .owl-dot {
				&:hover,
				&.active {
					span {
						background-color: @theme_color;
					}
				}
			}
		
			.shop-services .owl-carousel .owl-nav .owl-next, .shop-services .owl-carousel .owl-nav .owl-prev {
				&:hover {
					color: @theme_color;
				}
			}
		
			.title-block h2:before {
				background-color: @theme_color;
			}
		
			.title-block a:hover {
				color: @theme_color;
			}
		
			.product-slider .owl-theme .owl-nav div:hover {
				background-color: @theme_color;
				border-color: @theme_color;
			}
		
			.brand-slider .owl-carousel .owl-nav .owl-next,
			.brand-slider .owl-carousel .owl-nav .owl-prev {
				&:hover {
					color: @theme_color;
				}
			}
		
			.categories-item .group-cat:hover {
				background-color: @theme_color;
				border-color: @theme_color;
			}
		
			.categories-item .owl-theme .owl-nav div:hover {
				background-color: @theme_color;
			}
		}
		
		.home-page-2{
			.slidershow .owl-theme .owl-nav {
				.owl-next:hover,
				.owl-prev:hover {
					background-color: @theme_color;
				}
			}
		
			.slidershow .owl-theme .owl-dots .owl-dot {
				&:hover,
				&.active {
					span {
						background-color: @theme_color;
					}
				}
			}
			
			.title-block .view-all a:hover{
				border-color: @theme_color;
				color: @theme_color;
			}
			
			.tab-products-banner .ltabs-wrap .ltabs-tabs-container .ltabs-tabs-wrap ul li{
				&.tab-sel,
				&:hover{
					color: @theme_color;
				}
				
				&:not(:last-child) span:after {
					background-color: @theme_color;
				}
			}
			
			.tab-products-banner .sm-listing-tabs .ltabs-items .ltabs-loadmore .ltabs-loadmore-btn:hover{
				background-color: @theme_color;
			}
			
			.deal-content .count-container .deals-countdown{
				background-color: @theme_color;
			}
			
			.deal-content .title-block h2:before {
				color: @theme_color;
			}
			
			.view-all-bottom a:hover{
				background-color: @theme_color;
			}
			
			.product-slider-content .owl-theme .owl-nav div:hover{
				background-color: @theme_color;
				border-color: @theme_color;
			}
		}
		
		.home-page-3{
			.group-banner-slider .owl-theme .owl-dots .owl-dot:hover span{
				border-color: @theme_color;
			}
			
			.group-deal .left-block-title{
				background-color: @theme_color;
			}
			
			.tab-slider .ltabs-wrap .ltabs-tabs li{
				&:hover,
				&.tab-sel{
					color: @theme_color;
				}
			}
			
			.group-banner-item.group-video a span:hover{
				background-color: @theme_color;
			}
			
			.tab-slider .product-item .item-inner .product-item-details .number-item{
				color: @theme_color;
			}
		}
		
		/* END HOME */
		
		/* FOOTER */
		.footer-style-1 {
			a:hover {
				color: @theme_color;
			}
		
			.copyright-footer a {
				color: @theme_color;
			}
		}
		
		.footer-style-2 {
			.block-footer .block-footer-content ul li a{
				b{
					color: @theme_color;
				}
				
				&:hover {
					color: @theme_color;
			
					&:before {
						color: @theme_color;
					}
				}
			}
			
			&.footer-container .socials-wrap ul li a:hover{
				background-color: @theme_color;
			}
		}
		
		.footer-style-3 {
			border-top: 2px solid @theme_color;
			
			.seo-struct ul li a:hover{
				color: @theme_color;
			}
			
			.block-footer .block-footer-content ul li a:hover{
				color: @theme_color;
			}
		}
			
		/* END FOOTER */
		
		/* BONUS */
		
		.cart-container .cart.main.actions .action,
		.cart-container .cart.table-wrapper .actions-toolbar .action-edit:hover,
		.cart-container .cart.table-wrapper .actions-toolbar .action-delete:hover,
		.cart-container .checkout-methods-items .action.primary.checkout {
			background-color: @theme_color;
		}
		
		.store-info-contact ul li:hover {
			.icon-info-contact {
				background-color: @theme_color;
				border-color: @theme_color;
			}
		}
		
		.title-contact-page h2:before {
			background-color: @theme_color;
		}
		
		.grid-about .grid-items .item-about .info-about .title-about a:hover,
		.post-list .post-text-hld .post-title a:hover,
		.post-list .post-text-hld .read-more-post a:hover {
			color: @theme_color;
		}
		
		.post-ftimg-hld .date-post {
			background-color: @theme_color;
		}
		
		/* END BONUS */
		
		/* PAGE */
		.post-list .post-categories a:hover {
			color: @theme_color;
		}
		
		.w-newsletter .newsletter-info .socials-wrap ul li a:hover {
			background-color: @theme_color;
			border-color: @theme_color;
		}
		
		/* END PAGE */
		
		// RESPONSIVE
		
		@media (min-width: 1200px) {
		
		}
		
		@media (min-width: 992px) and (max-width: 1199px) {
		
		}
		
		@media (min-width: 768px) and (max-width: 991px) {
		
		}
		
		@media (max-width: 768px) {
			.resp-accordion.resp-tab-active {
				background-color: @theme_color;
				border-color: @theme_color;
			}
		}
		
		@media (max-width: 480px) {
		
		}
	";
?>