<?php
/**
 *
 * SM Listing Tabs - Version 2.6.0
 * Copyright (c) 2017 YouTech Company. All Rights Reserved.
 * @license - Copyrighted Commercial Software
 * Author: YouTech Company
 * Websites: http://www.magentech.com
 */
 
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
if ($this->_isAjax()) {
	$products = $this->_ajaxLoad();
	$config = $this->_getConfig();
}else{
	$config = $this->getData('config');
	$products = $this->getData('products');
}			
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_config         = $this->helper('Sm\Metro\Helper\Data');
$homeStyle       = $_config->getThemeLayout('home_style');
$viewMode = 'grid';
$image = 'category_page_grid';
$showDescription = false;
$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;

$type_loadmore = $config['type_show'] == 'loadmore' ? true : false;
$cls_mark = $type_loadmore ? ' ltabs-mark ' : '';
$count_item         = count($products);
if (count($products)){
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class=" <?php /* @escapeNotVerified */ echo $viewMode; ?> tab-list-slider">
        <?php $iterator = 1; ?>
        <div class="products list items product-items  <?php echo $type_loadmore == false ? ' owl-carousel owl-theme' : ''; ?>"  <?php echo $type_loadmore ?  'data-liffect="fadeIn"' : '' ;?>>
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php 
			$j       = 0;
			$count   = 0;
			$nb_rows =  $config['slider_row'];
			foreach ($products as $_product): 
			$count++;
			$j++;
			?>	
				<?php if ($count % $nb_rows == 1 || $nb_rows == 1) { ?>
                <div class="item product product-item">
				<?php } ?>
                <div class="product-item-info" data-container="product-grid">
				
                    <div class="item-inner">
						<?php
						$productImage = $block->getImage($_product, $image);
						if ($pos != null) {
							$position = ' style="left:' . $productImage->getWidth() . 'px;'
								. 'top:' . $productImage->getHeight() . 'px;"';
						}
						?>

						<?php // Product Image
						?>
                        <div class="box-image-list">
							<a href="<?php /* @escapeNotVerified */
							echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
								<?php echo $productImage->toHtml(); ?>
							</a>
						</div>
						
						<div class="product details product-item-details box-info">
							<div class="number-item">
								<?php echo $j; ?>
							</div>
							<?php
							$_productNameStripped = $block->stripTags($_product->getName(), null, true);
							?>
                            <h2 class="product name product-item-name product-name">
								<a class="product-item-link"
                                   href="<?php /* @escapeNotVerified */
								   echo $_product->getProductUrl() ?>">
									<?php /* @escapeNotVerified */
									echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
								</a>
							</h2>

							<?php /* @escapeNotVerified */
							echo $block->getProductPrice($_product) ?>
							<?php echo $block->getProductDetailsHtml($_product); ?>
							<?php echo $block->getReviewsSummaryHtml($_product, $templateType, true); ?>

							<?php
							if ((int)$config['display_countdown'] && !empty($_product->getSpecialPrice()) && !empty($_product->getSpecialToDate())) {
								$specialToDate = $_product->getSpecialToDate();
								?>
                                <div class="deals-countdown" data-timer="<?php echo date("Y/m/d H:i:s", strtotime($specialToDate)); ?>">
								<div class="deals-time time-day"><div class="num-time"></div><div class="title-time"></div></div>
								<div class="deals-time time-hours"><div class="num-time"></div><div class="title-time"></div></div>
								<div class="deals-time time-mins"><div class="num-time"></div><div class="title-time"></div></div>
								<div class="deals-time time-secs"><div class="num-time"></div><div class="title-time"></div></div>
							</div>
							<?php } ?>
						</div>
					</div>
				
                </div>
				<?php if (($count % $nb_rows == 0 || $count == $count_item)) { ?>
                </div>
				<?php } ?>
            <?php endforeach; ?>
        </div>
    </div>
<?php 
} else {
	  if (!$this->_isAjax()) { ?> 
		 <div class="message info empty"><div><?php /* @escapeNotVerified */ echo __('We can\'t find products matching the selection.') ?></div></div>
<?php }
} ?>